services:
  db:
    image: postgres:14-alpine
    container_name: db
    hostname: db
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - dev-network
    volumes:
      - db:/var/lib/postgresql/data 

networks:
  dev-network:
    driver: bridge

volumes:
  db: {}
